### ISSUE TITLE
В SmartDictionary добавить методы:

### ISSUE THREAD

**Issue by vikk777** [vikk777/Smart-Dictionary#1]
1. 
- [x] isEmpty(): bool - проверка на пустоту
- [x] dictionary(str): Dictionary - возвращаемый тип **НЕ Dictionary**, а список списков слов:
`[  
    ['hello', 'привет'],  
    ['world', 'мир', 'ворлд'],  
    ...  
]`
Или список кортежей, что лучше.
- [x] dictionariesList(): list(str) - удалить
- [x] dictionaries(): list(str) - список кортежей имен словарей и их описаний
`(name', 'description')`
- [x] quantity(str): int - количество слов в словаре str
- [x] totalWords(): int - общее количество слов

- [x] addWord(str, str, str, str):
- [x] changeWord(str, str, str, str, str):
- [x] deleteWord(str, str) 

- [x] changeDictionary(str, str, str): bool

2. 
- [x] добавить метод words, который будет возвращать слова по имени словаря. Вместо метода dictionary.
- [x] метод dictionary должен возвращать кортеж из имени и описания словаря по имени словаря.

Название файла - smart_dictionary.py

**Comment by Sherifffox** [comment]
Название файла - smart_dictionary.py +

**Comment by Sherifffox** [comment]
-  addWord (str, str, str, str): одна str - это название словаря, если пусто '', то в дефолтный словарь добавляется слово

**Comment by vikk777** [comment]
> * addWord (str, str, str, str): одна str - это название словаря, если пусто '', то в дефолтный словарь добавляется слово

+ Название словаря обязательно на первом месте. Транскрипция - последний аргумент необязателен.

**Comment by vikk777** [comment]
+ addWord(str, str, str, str):
+ changeWord(str, str, str, str, str):
Добавить первым аргументом название словаря.

**Comment by Sherifffox** [comment]
- [deleteWord()]
