### ISSUE TITLE
Модуль Тест

### ISSUE THREAD

**Issue by vikk777** [vikk777/Smart-Dictionary#7]
### SmartDictionary
1. 
- [x] testQuestions(str): list - принимает имя словаря, возвращает список ключей слов.
- [x] testResult(dict()): int - принимает dict ответов, возвращает количество правильных слов.
 
2.
- [x] Разделить тест на вопросы.
- [x] Выбор по периоду. День, неделя, месяц.

3.
testQuestions заменить на testInit
testAnswers заменить на addAnswer
- [x] testInit(str): bool - выбирает нужные слова из словаря. Формат (original: translate). После чего добавляет к этому словарю инвертированный словарь в формате (translate: original).
- [x] nextQuestion(): str- возвращает вопрос. Если вопросы закончились, возвращает пустую строку.
- [x] addAnswer(tuple) - добавляет ответ в словарь ответов.
- [x] testResult(): int - больше не принимает значений.

4. 
- [x] testIsInit(): bool - возвращает True, если есть вопросы, False  в противном случае.

5. 
Сделать константы класса SmartDictionary:
MISTAKE_DICT = '\_\_mistake\_\_'
ALL_DICTS = '\_\_all\_\_'
- [x] testInit проверяет имя словаря, и в зависимости от него (оно может быть одной из констант) сохраняет в _questions нужный словарь: все, ошибочный или по имени.

6.
- [x] haveMistakes(): bool - Если ошибки есть, возвращает True. Иначе False

**Comment by Sherifffox** [comment]
- [ ] _wrongAnswers: dict() - добавить словарик с ошибками

- [ ]  возможность выбирать тестирование по словарю с ошибками

- [ ] возможность выбирать прямое/обратное тестирование или прямое&обратное

- [ ] исправить проверку check() - проверять регуляркой

- [ ]  продумать процесс тестирования с выбором ответа
